<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CTLINDT-0119" name="tv.hooq.web.scripts.HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent" tests="1" failures="1" timestamp="13 Apr 2017 05:42:26 GMT" time="0.003" errors="0">
  <testcase name="HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent" time="0.003" classname="tv.hooq.web.scripts.HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 4 parameters but the method tv.hooq.web.scripts.HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent#HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent takes 5 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 4 parameters but the method tv.hooq.web.scripts.HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent#HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent takes 5 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1361)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1359)
	... 17 more
]]>
    </failure>
  </testcase> <!-- HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent -->
</testsuite> <!-- tv.hooq.web.scripts.HOOQ_Web_TVOD_Find_Duplicate_Collection_Rent -->
