<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CTLINDT-0119" name="tv.hooq.web.scripts.Hooq_UserAccess" tests="2" failures="0" timestamp="26 Dec 2016 06:17:51 GMT" time="887.454" errors="1">
  <testcase name="Hooq_UserAccess" time="478.100" classname="tv.hooq.web.scripts.Hooq_UserAccess">
    <error type="java.lang.AssertionError" message="Step VerifyText  Failed with description &lt;b&gt;Subscribe to HOOQ&lt;/b&gt; is &lt;b&gt;NOT&lt;/b&gt; present in the location: &lt;b&gt;Subscribe to HOOQ&lt;/b&gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Step VerifyText  Failed with description <b>Subscribe to HOOQ</b> is <b>NOT</b> present in the location: <b>Subscribe to HOOQ</b> expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ctaf.support.HtmlReportSupport.onFailure(HtmlReportSupport.java:780)
	at com.ctaf.utilities.Reporter.failureReport(Reporter.java:92)
	at com.ctaf.accelerators.ActionEngine.verifyText(ActionEngine.java:1470)
	at tv.hooq.web.workflows.HOOQWorkflows.verifyTimesUpScreen(HOOQWorkflows.java:195)
	at tv.hooq.web.workflows.HOOQWorkflows.verifyPlaybackOfItem(HOOQWorkflows.java:266)
	at tv.hooq.web.scripts.Hooq_UserAccess.Hooq_UserAccess(Hooq_UserAccess.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- Hooq_UserAccess -->
  <testcase name="Hooq_UserAccess" time="409.354" classname="tv.hooq.web.scripts.Hooq_UserAccess"/>
</testsuite> <!-- tv.hooq.web.scripts.Hooq_UserAccess -->
